version: "3.7"
services:
  app:
    build:
      args:
        user: magicport
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: magic-port-app
    container_name: magic-port-container
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - magic-port-network

  db:
    image: mysql:8.0
    container_name: magic-port-db-container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - magic-port-network

  nginx:
    image: nginx:alpine
    container_name: magic-port-nginx-container
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - magic-port-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - magic-port-network

networks:
  magic-port-network:
    driver: bridge
